# Numpy_Note

## loadtxt(path, dtype, delimiter,converters): read a .txt/.data file

In [2]:
import numpy as np

def Iris_type(s):
    s= s.decode("UTF-8") # what text read is the b'Iris-setosa' like string, what I did here is to set proper decoding way 
    map1 = {'Iris-setosa': 0, 'Iris-versicolor': 1, 'Iris-virginica': 2}
    return map1[s]
 # we define the data type as float, delimiter as comma, and the 4th column as a number deriving from the function named Iris_type 
data = np.loadtxt('Iris.data',dtype = float, delimiter =',', converters = {4:Iris_type})
print(data[:5,:])

[[ 5.1  3.5  1.4  0.2  0. ]
 [ 4.9  3.   1.4  0.2  0. ]
 [ 4.7  3.2  1.3  0.2  0. ]
 [ 4.6  3.1  1.5  0.2  0. ]
 [ 5.   3.6  1.4  0.2  0. ]]


## reshape(a, newshape)

In [13]:
array1 = np.arange(9)
array2 =np.reshape(array1,(3,3)) # reshape the array1 to a 3x3 array
print(array2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [19]:
array1 = np.arange(10)
array2 =np.reshape(array1,10) # reshape the array to 1D array with the length of 10
print(array2)

[0 1 2 3 4 5 6 7 8 9]


In [22]:
array1 = np.array([[1,2,3],[4,5,6]])
array2 =np.reshape(array1,[3,-1]) # reshape the array to 3 rows and the compatible columns
print(array2)

[[1 2]
 [3 4]
 [5 6]]


In [25]:
array1 = np.arange(10)
array2 =np.reshape(array1,[5,-1]) # reshape the array to 5 rows and the compatible columns
print(array2)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [26]:
array1 = np.array([[1,2,3],[4,5,6]])
array2 =np.reshape(array1,[3,-1],order = 'F') # reshape the array to 3 rows and the compatible columns
print(array2)

[[1 5]
 [4 3]
 [2 6]]


## object.ravel()

In [28]:
# ravel is equivalent to reshape(-1)
array1 = np.arange(10).reshape(2,5)
print('array1: \n', array1)
print('array1.reshape(-1)\n',array1.reshape(-1))
print('array1.ravel()\n',array1.ravel())

array1: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array1.reshape(-1)
 [0 1 2 3 4 5 6 7 8 9]
array1.ravel()
 [0 1 2 3 4 5 6 7 8 9]


## linspace(from,to,total No.)

In [31]:
# create evenly spaced numbers with particular intervals
array1 = np.linspace(0,1,11)  # interval = (max-min)/(number-1)
print(array1)

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1. ]


## split(ary, indices_or_sections, axis = 0)

In [35]:
array1 = np.arange(10)
print(np.split(array1,5)) # equally split to 5 lists

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


In [36]:
array1 = np.arange(10)
print(np.split(array1,(2,8))) # equally split at 2nd and 8th character

[array([0, 1]), array([2, 3, 4, 5, 6, 7]), array([8, 9])]


In [42]:
array1 = np.array([[0,1,2,3],[6,7,8,9]])
print(np.split(array1,5,axis = 1)) # equally split to 5 lists based on the 2nd dimention (in this example is column)

[array([[0],
       [5]]), array([[1],
       [6]]), array([[2],
       [7]]), array([[3],
       [8]]), array([[4],
       [9]])]


## meshgrid()

x1, x2,..., xn : array_like

1-D arrays representing the coordinates of a grid.

indexing : {‘xy’, ‘ij’}, optional

Cartesian (‘xy’, default) or matrix (‘ij’) indexing of output. See Notes for more details.

New in version 1.7.0.

sparse : bool, optional

If True a sparse grid is returned in order to conserve memory. Default is False.

New in version 1.7.0.

copy : bool, optional

If False, a view into the original arrays are returned in order to conserve memory. Default is True. Please note that sparse=False, copy=False will likely return non-contiguous arrays. Furthermore, more than one element of a broadcast array may refer to a single memory location. If you need to write to the arrays, make copies first.

New in version 1.7.0.

In [5]:
x = np.linspace(-5,5,11)
y = np.linspace(-1,1,3)
print(array1,array2)
xx, yy = np.meshgrid(x,y)
print(xx)
print(yy)

[-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.] [-1.  0.  1.]
[[-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]
 [-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]
 [-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]]
[[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


In [9]:
array1 = np.arange(1,7).reshape(2,3)
print(array1)
x = array1.flat
print(x)


[[1 2 3]
 [4 5 6]]
